<table class="table table-bordered table-striped table-hover table-reponsive scroll">
    <thead>
        <a href="<?php echo $block->getBaseUrl(); ?>blog/index/create" 
        style="text-decoration: none;border-radius:8px; color:white; background-color:#28a745; padding:8px 16px;" 
        class="btn btn-primary btn-xs pull-right">Create New Post</a>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Content</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $posts = $block->getPosts();

        foreach ($posts as $post) :
        ?>
            <tr style="border: 1px solid #dddddd; text-align: left; padding: 8px;">
                <td><?php echo $post->getId(); ?></td>
                <td><?php echo $post->getName(); ?></td>
                <td><?php echo $post->getContent(); ?></td>
                <td>
                    <a href="<?php echo $block->getBaseUrl(); ?>blog/index/edit/post_id/<?php echo $post->getId(); ?>" style="text-decoration: none;border-radius:8px; color:white; background-color:#117a8b; padding:8px 16px;">Edit</a>
                </td>
                <td>
                    <a href="<?php echo $block->getBaseUrl(); ?>blog/index/delete/post_id/<?php echo $post->getId(); ?>" style="text-decoration: none;border-radius:8px; color:white; background-color:#bd2130; padding:8px 16px;">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>